### PR TITLE
Create audiosear.ch patch.yaml

### PR DESCRIPTION
**Pull request by oliver-xapix-io**
#64 second option I suggested

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@oliver-xapix-io Cool :+1: 
Can you please rename `patch.yml` into `patch.yaml`.

**Comment by oliver-xapix-io** [comment]
@IvanGoncharov How about my last comment in #64 ? I feel we should decide that first.

**Comment by IvanGoncharov** [comment]
@oliver-xapix-io Before I merge, please squash your commits into one and give it more descriptive message something like `Added  x-apiClientRegistration for audiosear.ch API`.

**Comment by oliver-xapix-io** [comment]
@IvanGoncharov I guess I did what you asked me to do. But I did it for the first time in my life so please doublecheck.

**Comment by IvanGoncharov** [comment]
@oliver-xapix-io Everything cool.
You can use `git commit --amend` when you fix your PR, it allow you to change top commit instead of creating a new one. And you don't need to squash in the end.

The only thing that I saw is `oliver-xapix-io committed with pickledolives`, you probably use different accounts on different machines. But it's not a problem so I merged PR.

Thank you for contribution :+1:

**Comment by oliver-xapix-io** [comment]
I use 2fa secured root accounts that own all my digital stuff and do payment and I do everyday work with more convenient collaborater role accounts, that's why.

In this particular case I created the file directly in Github and edited it there according to your demands. Github made the 2 commits. I finally still had to clone and rebase with squash to make it 1 commit.

I am gonna make my way through the API list and write auth adapter snippets for all the APIs. I'll commit the key creation links along the way.

**Comment by IvanGoncharov** [comment]
@oliver-xapix-io It would be great. You can create PR for with one or multiple APIs, both will work for me.
Same goes for commits you can add multiple APIs into one commit.
If you want to change something in the last commit use `git commit --amend` it super easy.

**Pull request merged**
