### PR TITLE
Update openapi.yaml

### PR DESCRIPTION
**Pull request by JohnnyMaxK**
Remove ebay token

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks for the PR. If we merged this though, it would get overwritten by the canonical version we're pulling from https://api-docs.beezup.com/swagger.json - I've just updated from that URL and there were no changes to the published version.

Are you able / planning to update the version at that URL?

**Comment by Johnny-Bee** [comment]
I have updated the documentation. Please help me to do update. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeRalphson** [comment]
I'd just done the weekly update before your change, but I've now re-run it just for your API and it has picked up the changes. Thanks.

**Comment by Johnny-Bee** [comment]
Thanks 🙏

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
