### PR TITLE
Afterbanks; The type for 'documentType' should be `integer` since the format is `int32`.

### PR DESCRIPTION
**Pull request by garydgregory**
The type for 'documentType' should be `integer` since the format is `int32`.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Hi @garydgregory thanks for the PR. Unfortunately, we can't accept PRs directly on the `swagger.yaml` files - see [CONTRIBUTING.md](https://github.com/APIs-guru/openapi-directory/blob/master/CONTRIBUTING.md) for the why's and wherefore's.

Best of all would be getting this fixed upstream to benefit everyone, but I can accept a PR which adds a `fixup.yaml` file.

**Comment by garydgregory** [comment]
Gotcha, thank you for the feedback. I'm new on this project. I'll see about a PR in the AM.

**Comment by MikeRalphson** [comment]
Ping?

**Comment by MikeRalphson** [comment]
Closing due to inactivity - but please feel free to reopen the issue if necessary.

**Pull request closed without merging**
