### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/openapi-directory ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by monkeywithacupcake** [comment]
You already had badges on the README. I tried to fix them, so that they pull from the right source and add images at the bottom. However, something is wrong. Backers and partners are somehow getting mixed. I'll update this PR once I get in touch with some other folks from Open Collective.

**Comment by MikeRalphson** [comment]
Hi @monkeywithacupcake - any progress with getting the badges to display correctly?

**Comment by MikeRalphson** [comment]
Ping @monkeywithacupcake

**Comment by monkeywithacupcake** [comment]
Thanks for the ping - this is actually working right for backers and sponsors. There is no badge for your custom setting "partners" it turns out. Also, the reason that there is no image for your backer is because the backer does not have an image. If you look on the open collective site: https://opencollective.com/openapi-directory#contributors you will see that there is just a ghost image.

**Comment by MikeRalphson** [comment]
Many thanks.

**Pull request merged**
