### PR TITLE
Added opendatanetwork.com API

### PR DESCRIPTION
**Pull request by westernmagic**

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Many thanks for the contribution, and kudos for doing it as a PR! Is there a logo or Twitter account associated with this API?

**Comment by westernmagic** [comment]
Twitter: don't think so
Logo: yes, but I can't find an image link; the website has a logo that is embededd in the CSS.

**Comment by MikeRalphson** [comment]
Found https://21bqi49zoy82acfw93qlpqm1-wpengine.netdna-ssl.com/wp-content/uploads/tyler-socrata-logos.png - I can always add that later.

Many thanks again for the contribution!

**Comment by westernmagic** [comment]
Not quite the one on this website though:
https://www.opendatanetwork.com/

**Pull request merged**
