### PR TITLE
swagger file for v1 of OpenCage geocoding API

### PR DESCRIPTION
**Pull request by freyfogle**
Hi,
here's a swagger file for the OpenCage Geocoder
https://geocoder.opencagedata.com/api

My first time playing with swagger, all feedback welcome

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@freyfogle Great :+1: 
Can you please host Swagger file in official Github repo or on your backend.
APIs.guru aggregate API spec and doesn't host them, so I just need stable URL to swagger spec.
I will update it, see this: https://github.com/APIs-guru/api-models#update-procedure

P.S. It allow more flexibility on your side :)
IMHO, sending PRs each time you want to correct your swagger file is overkill.

**Comment by freyfogle** [comment]
ok, I have now added an x-origin tag. Please let me know if anything else is needed. 

One tip - if x-origin is important you should add it to the tutorial / docs, I just followed whatever was there.

**Comment by IvanGoncharov** [comment]
@freyfogle Thank you. I added you API into collection manually since current workflow don't work well with PRs.

I started this project by adding 200+ APIs on my own.
So currently all workflows tied to running some undocumented scripts.
But we working on making it open for other developers to contribute.

> One tip - if x-origin is important you should add it to the tutorial / docs, I just followed whatever was there.

We plan to add "Add API" online form on https://APIs.guru in the next few days
It should solve most of the problems.
Then we will have a working prototype I send you a link.
It would be great to get feedback from you.

**Comment by IvanGoncharov** [comment]
> We plan to add "Add API" online form on https://APIs.guru in the next few days
It should solve most of the problems.
Then we will have a working prototype I send you a link.
It would be great to get feedback from you.

@freyfogle Here is a link: http://apis-guru.github.io/add-api/

**Pull request closed without merging**
