### PR TITLE
Giphy API definition

### PR DESCRIPTION
**Pull request by faragorn**
Definition for Giphy API: https://developers.giphy.com/docs/
Supports everything their documentation describes.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Hi @faragorn thanks for the submisison. Unfortunately I can't merge a PR to add a new API directly for a couple of reasons:

* APIs-guru aggregates API definitions, but doesn't **host** the source-of-truth for them
* the definitions require a few specification-extensions added in order to 'round-trip' the process of keeping them up-to-date - the Travis build failed for this reason, these are managed by a series of node.js scripts

So we have a couple of options, either I can add the definition using a github-raw link to your repo as the source, or we can add the definition to [another repo](https://github.com/APIs-guru/unofficial_openapi_specs) we use for this purpose - i.e. API definitions which have been reverse-engineered from API documentation etc.

*Or*

you can clone the repo locally, if you haven't already done so, and run the following

* create a new branch for the PR
* change into the `APIs` directory
* run `../scripts/collection add -c {category} -l {logo-path} swagger_2 {url-to-definition}'

Where `{category}` is one of the values from `/resources/categories.yaml`

**Comment by faragorn** [comment]
@MikeRalphson Thanks for the instructions, I was able to do it myself. The build is running now. Let's see

**Comment by MikeRalphson** [comment]
Looks pretty good, I just have a question about the `url` property within the `x-origin` extension, has that been hand-edited? It needs to be a URL to the source swagger definition to allow round-tripping updates.
`giphy.com/1.0/swagger.yaml` just 404s for me?

**Comment by faragorn** [comment]
Ok, I think it is done right this time. I also added `unofficial` flag

**Comment by MikeRalphson** [comment]
Brilliant stuff! Many thanks. Obviously with any other APIs from your library project, the process will be similar.

**Comment by faragorn** [comment]
Thanks! Yeah, should be more smooth next time. And if I make any updates I can commit them to my repo and run  `collection update` script for this repo?

**Comment by MikeRalphson** [comment]
Yes, you can also run `../scripts/collection update {directory}` to only update one directory, but we run update across the whole collection at least once a week anyway.

**Pull request merged**
