### PR TITLE
Update x-logo-url in configcat.com/patch.yaml

### PR DESCRIPTION
**Pull request by configcat**
We would like to use this svg for configcat logo:
https://configcat.com/images/shared/configcat-logo-vert.svg

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks. Please bear in mind that if this image is removed from that URL it will break our deployment process. In that case we would revert to the Twitter avatar and would probably insist you add the `x-logo` extension yourself if you wished to change it again.

**Comment by configcat** [comment]
Thanks. What is strange to me that the original twitter URL: https://twitter.com/configcat/profile_image?size=original doesn’t exist. I think this kind of URL is not supported by twitter anymore. Do you experience the same?

How does it work on your side? When will this API available on https://apis.guru/browse-apis?

**Comment by MikeRalphson** [comment]
Those urls work fine outside a browser. The new logo should have been deployed about 5 minutes ago.

**Comment by configcat** [comment]
Thanks.

**Pull request merged**
